[project]
name = "arseille"
version = "0.1.0"
description = "Arseille is a customized vending machine enhanced with real-time image processing"
readme = "README.md"
authors = [
    { name = "jfpiedad", email = "jfpiedad@gmail.com" }
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "albumentations>=2.0.8",
    "cachetools>=6.2.1",
    "fastapi[standard-no-fastapi-cloud-cli]>=0.118.0",
    "matplotlib>=3.10.7",
    "mediapipe>=0.10.21",
    "pandas>=2.3.3",
    "pydantic-settings>=2.11.0",
    "pymongo>=4.15.3",
    "torch>=2.9.0",
    "torchvision>=0.24.0",
    "tqdm>=4.67.1",
]

[project.scripts]
arseille = "arseille:main"

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "httpx-ws>=0.8.2",
    "pytest>=9.0.1",
    "respx>=0.22.0",
    "ruff>=0.13.3",
]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
]
ignore = [
    "B008",  # do not perform function calls in argument defaults
    "B904",  # Allow raising exceptions without from e, for HTTPException
]
