[project]
name = "ml-models"
version = "0.1.0"
description = "ML models used in vending"
readme = "README.md"
authors = [
    { name = "jfpiedad", email = "jfpiedad@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "albumentations>=2.0.8",
    "click>=8.3.0",
    "matplotlib>=3.10.6",
    "pandas>=2.3.3",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
    "tqdm>=4.67.1",
    "typer>=0.19.2",
]

[project.scripts]
ml-models = "ml_models:main"

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"
