/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionDetailsRouteImport } from './routes/transaction-details'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendingMachineIndexRouteImport } from './routes/vending-machine/index'
import { Route as VendingMachineFullSystemRouteImport } from './routes/vending-machine/full-system'
import { Route as VendingMachineCheckpoint75RouteImport } from './routes/vending-machine/checkpoint75'
import { Route as VendingMachineCheckpoint50RouteImport } from './routes/vending-machine/checkpoint50'
import { Route as VendingMachineCheckpoint25RouteImport } from './routes/vending-machine/checkpoint25'

const TransactionDetailsRoute = TransactionDetailsRouteImport.update({
  id: '/transaction-details',
  path: '/transaction-details',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendingMachineIndexRoute = VendingMachineIndexRouteImport.update({
  id: '/vending-machine/',
  path: '/vending-machine/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendingMachineFullSystemRoute =
  VendingMachineFullSystemRouteImport.update({
    id: '/vending-machine/full-system',
    path: '/vending-machine/full-system',
    getParentRoute: () => rootRouteImport,
  } as any)
const VendingMachineCheckpoint75Route =
  VendingMachineCheckpoint75RouteImport.update({
    id: '/vending-machine/checkpoint75',
    path: '/vending-machine/checkpoint75',
    getParentRoute: () => rootRouteImport,
  } as any)
const VendingMachineCheckpoint50Route =
  VendingMachineCheckpoint50RouteImport.update({
    id: '/vending-machine/checkpoint50',
    path: '/vending-machine/checkpoint50',
    getParentRoute: () => rootRouteImport,
  } as any)
const VendingMachineCheckpoint25Route =
  VendingMachineCheckpoint25RouteImport.update({
    id: '/vending-machine/checkpoint25',
    path: '/vending-machine/checkpoint25',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/transaction-details': typeof TransactionDetailsRoute
  '/vending-machine/checkpoint25': typeof VendingMachineCheckpoint25Route
  '/vending-machine/checkpoint50': typeof VendingMachineCheckpoint50Route
  '/vending-machine/checkpoint75': typeof VendingMachineCheckpoint75Route
  '/vending-machine/full-system': typeof VendingMachineFullSystemRoute
  '/vending-machine/': typeof VendingMachineIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/transaction-details': typeof TransactionDetailsRoute
  '/vending-machine/checkpoint25': typeof VendingMachineCheckpoint25Route
  '/vending-machine/checkpoint50': typeof VendingMachineCheckpoint50Route
  '/vending-machine/checkpoint75': typeof VendingMachineCheckpoint75Route
  '/vending-machine/full-system': typeof VendingMachineFullSystemRoute
  '/vending-machine': typeof VendingMachineIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/transaction-details': typeof TransactionDetailsRoute
  '/vending-machine/checkpoint25': typeof VendingMachineCheckpoint25Route
  '/vending-machine/checkpoint50': typeof VendingMachineCheckpoint50Route
  '/vending-machine/checkpoint75': typeof VendingMachineCheckpoint75Route
  '/vending-machine/full-system': typeof VendingMachineFullSystemRoute
  '/vending-machine/': typeof VendingMachineIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/transaction-details'
    | '/vending-machine/checkpoint25'
    | '/vending-machine/checkpoint50'
    | '/vending-machine/checkpoint75'
    | '/vending-machine/full-system'
    | '/vending-machine/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/transaction-details'
    | '/vending-machine/checkpoint25'
    | '/vending-machine/checkpoint50'
    | '/vending-machine/checkpoint75'
    | '/vending-machine/full-system'
    | '/vending-machine'
  id:
    | '__root__'
    | '/'
    | '/transaction-details'
    | '/vending-machine/checkpoint25'
    | '/vending-machine/checkpoint50'
    | '/vending-machine/checkpoint75'
    | '/vending-machine/full-system'
    | '/vending-machine/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TransactionDetailsRoute: typeof TransactionDetailsRoute
  VendingMachineCheckpoint25Route: typeof VendingMachineCheckpoint25Route
  VendingMachineCheckpoint50Route: typeof VendingMachineCheckpoint50Route
  VendingMachineCheckpoint75Route: typeof VendingMachineCheckpoint75Route
  VendingMachineFullSystemRoute: typeof VendingMachineFullSystemRoute
  VendingMachineIndexRoute: typeof VendingMachineIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transaction-details': {
      id: '/transaction-details'
      path: '/transaction-details'
      fullPath: '/transaction-details'
      preLoaderRoute: typeof TransactionDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vending-machine/': {
      id: '/vending-machine/'
      path: '/vending-machine'
      fullPath: '/vending-machine/'
      preLoaderRoute: typeof VendingMachineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vending-machine/full-system': {
      id: '/vending-machine/full-system'
      path: '/vending-machine/full-system'
      fullPath: '/vending-machine/full-system'
      preLoaderRoute: typeof VendingMachineFullSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vending-machine/checkpoint75': {
      id: '/vending-machine/checkpoint75'
      path: '/vending-machine/checkpoint75'
      fullPath: '/vending-machine/checkpoint75'
      preLoaderRoute: typeof VendingMachineCheckpoint75RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vending-machine/checkpoint50': {
      id: '/vending-machine/checkpoint50'
      path: '/vending-machine/checkpoint50'
      fullPath: '/vending-machine/checkpoint50'
      preLoaderRoute: typeof VendingMachineCheckpoint50RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vending-machine/checkpoint25': {
      id: '/vending-machine/checkpoint25'
      path: '/vending-machine/checkpoint25'
      fullPath: '/vending-machine/checkpoint25'
      preLoaderRoute: typeof VendingMachineCheckpoint25RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TransactionDetailsRoute: TransactionDetailsRoute,
  VendingMachineCheckpoint25Route: VendingMachineCheckpoint25Route,
  VendingMachineCheckpoint50Route: VendingMachineCheckpoint50Route,
  VendingMachineCheckpoint75Route: VendingMachineCheckpoint75Route,
  VendingMachineFullSystemRoute: VendingMachineFullSystemRoute,
  VendingMachineIndexRoute: VendingMachineIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
